language: cpp
sudo: required
dist: trusty

# Compiler selection
matrix: 
  include:
    - compiler: gcc

      addons:
        apt:
          sources:
            - kubuntu-backports
#            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
          packages:
            - g++-5

before_install:
#   - sudo apt-get purge cmake -y
#  - sudo wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
#  - tar zxf cmake-3.2.1-Linux-x86_64.tar.gz
#  - export PATH=`pwd`/cmake-3.2.1-Linux-x86_64/bin:$PATH
- pip install --user cpp-coveralls

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script: 
 # - sudo apt-get purge cmake -y 
 # - sudo apt-get install software-properties-common 
 # - yes '' | sudo add-apt-repository ppa:george-edison55/cmake-3.x
 # - sudo apt-get update  
 # - sudo apt-get install cmake -y
  - mkdir build 
  - cd build 
  - --enable-gcov
  - cmake ../  && make
  - cd src
  - ./hello

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
